# Generated by Django 3.2.5 on 2021-07-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_cart',
            name='token',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='token USER'),
        ),
    ]
